[package]
name = "rust-postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = [ "full" ] }
sqlx = { version = "0.7.2", features = [ "postgres", "runtime-tokio-rustls", "macros", "chrono", "uuid" ] }
axum = { version = "0.6.20", features = [] }
serde = "1.0.192"
dotenvy = "0.15.7"
chrono = { version = "0.4.31", features = [ "serde" ] }
uuid = { version = "1.5.0", features = [ "v4", "serde" ] }
